-- 매출 데이터 테이블
CREATE TABLE IF NOT EXISTS sales_records (
  id BIGSERIAL PRIMARY KEY,
  매입처 TEXT NOT NULL,
  제조사 TEXT NOT NULL,
  매출처 TEXT NOT NULL,
  제품명 TEXT NOT NULL,
  보험코드 TEXT,
  기준가 NUMERIC NOT NULL DEFAULT 0,
  실매입단가 NUMERIC NOT NULL DEFAULT 0,
  실이익금액 NUMERIC NOT NULL DEFAULT 0,
  실이익율 NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
